; initialize_console@0()
; returns void
extern initialize_console@0 : proc

; readLine@0()
; returns buffer ptr
extern readLine@0 : proc

; readLine_simple@0()
; returns buffer ptr
extern readLine_simple@0 : proc

; writeLine@8(* data, dataLength)
; returns void
extern writeLine@8 : proc

; writeString@4(* char)
; returns void
extern writeString@4 : proc

; clearConsole@0()
; output: void
extern clearConsole@0 : proc

; scrollConsole@0()
; output: void
extern scrollConsole@0 : proc